spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  freemarker:
    cache: 'false'
  datasource:
    url: jdbc:mariadb://localhost:3306/3jo?serverTimezone=Asia/Seoul&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    username: root
  devtools:
    livereload:
      enabled: 'true'
itemImgLocation: C:\work\SpringBoot-Project\src\main\resources\static\img\images\item
uploadPath: file:C:\work\SpringBoot-Project\src\main\resources\static\img\images\item

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
